name: lottie_example
description: A sample app for the Lottie player
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit:

dependency_overrides:
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottiefiles/
    - assets/Mobilo/
    - assets/Tests/
    - assets/Logo/
    - assets/Images/
    - assets/Images/WeAccept/

  fonts:
    - family: Comic Neue
      fonts:
        - asset: assets/fonts/Comic-Neue.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/Helvetica-Neue.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open-Sans.ttf
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PT-Serif.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf