name: lottie
description: Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
version: 0.6.1
homepage: https://github.com/xvrh/lottie-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.0
  characters: '>=0.5.0 <2.0.0'
  charcode: ^1.0.0
  collection: ^1.14.0
  logging: ^0.11.0
  meta: ^1.1.8
  path: ^1.6.0
  vector_math: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 0.39.14
  dart_style: 1.3.6
  mockito: ^4.0.0
  yaml:
