name: lottie
description: Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
version: 0.1.4
homepage: https://github.com/xvrh/lottie-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.0
  charcode: ^1.0.0
  vector_math: ^2.0.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml:
  analyzer:
  dart_style:
  path:

dependency_overrides:
  pedantic: ^1.9.0
