name: lottie
description: Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
version: 1.2.2
homepage: https://github.com/xvrh/lottie-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.0.0
  flutter:
    sdk: flutter
  path: ^1.8.0
  vector_math: ^2.1.0

dev_dependencies:
  analyzer:
  build_runner:
  dart_style:
  flutter_lints:
  flutter_test:
    sdk: flutter
  pub_semver:
  yaml:
