name: Lottie Flutter
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze_and_test:
    name: Flutter analyze
    strategy:
      matrix:
        flutter: ['stable', 'dev']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter }}
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
        working-directory: example
      - run: flutter analyze
      - run: flutter test test # https://github.com/flutter/flutter/issues/20907
      - run: flutter test test
        working-directory: example
      - run: flutter pub run tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
        shell: bash